name: vase
description: A simple wallet.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.6.1+30

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  qr_flutter: ^4.0.0
  web_socket_channel: ^2.1.0
  stream_channel: ^2.1.0
  json_annotation: ^4.3.0
  universal_html: ^2.0.8
  hex: ^0.2.0
  pointycastle: ^3.3.5
  collection: ^1.16.0
  sprintf: ^7.0.0
  unorm_dart: ^0.2.0
  buffer: ^1.1.1
  dartz: ^0.10.0
  provider: ^6.0.1
  flutter_secure_storage: ^6.0.0
  pool: ^1.5.0
  flutter_native_splash: ^2.2.11
  sentry_flutter: ^6.5.1
  flutter_hooks: ^0.18.2
  package_info_plus: ^3.0.1
  url_launcher: ^6.0.18
  go_router: ^5.1.1
  intl: ^0.17.0
  flutter_vibrate: ^1.3.0
  slide_to_confirm: ^1.1.0
  mobile_scanner: 3.0.0
  location: ^4.4.0
  protobuf: ^2.1.0
  fixnum: ^1.0.1
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.21.0
  mockito: ^5.0.16
  build_runner: ^2.3.0
  json_serializable: ^6.0.1
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icon/app_icon_android.png
  image_path_ios: assets/icon/app_icon_ios.png

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  fonts:
    - family: Brandon
      fonts:
        - asset: assets/fonts/Brandon-Regular.otf
        - asset: assets/fonts/Brandon-Medium.otf
          weight: 500
        - asset: assets/fonts/Brandon-Bold.otf
          weight: 700
